### ISSUE TITLE
make stuck at "awk -f abbr.awk  > cmd.hh"

### ISSUE THREAD

**Issue by BjWe** [arsv/sierracns#2]
Hi,

i am trying to compile sierracns on freebsd.
I'll use it on a pfsense firewall for a MC7710 4G card.

After executing 'make' it got stuck on "awk -f abbr.awk  > cmd.hh"

>b@:~ # git clone https://github.com/arsv/sierracns.git
>Cloning into 'sierracns'...
>remote: Counting objects: 188, done.
>remote: Total 188 (delta 0), reused 0 (delta 0), pack-reused 188
>Receiving objects: 100% (188/188), 46.06 KiB | 0 bytes/s, done.
>Resolving deltas: 100% (112/112), done.
>b@:~ # cd sierracns/
>b@:~/sierracns # make
>awk -f abbr.awk  > cmd.hh

Any ideas what is going wrong here?

**Comment by arsv** [comment]
awk waits for input. That command should read

    awk -f abbr.awk cmd.c cmd_gps.c cmd_poke.c cmd_watch.c cmd_query.c > cmd.hh

Is that a BSD make? Maybe try `gmake` instead of `make` if you have it installed.

**Comment by BjWe** [comment]
gmake works great.

but I have to make three small changes in main.c and wire.h.

main.c:
>#include <alloca.h>

to

>#ifdef __linux__
>#include <alloca.h>
>#endif
>#if defined(__FreeBSD__) || defined(__OpenBSD__)
>#include <stdlib.h>
>#define PTHREAD_BSD_SET_NAME
>#endif

in function "sigsetup":
delete line ".sa_restorer = NULL"

wire.h
>#if defined(__FreeBSD__) || defined(__OpenBSD__)
>#include <stdint.h>
>#endif


and I have found a complete documentation about all available cns commands: https://source.sierrawireless.com/resources/airprime/minicard/2130602_airprime_umts_mc_series_cns_reference/

**Comment by arsv** [comment]
Actually I don't think it needs #ifdef(*BSD) guarding, those changes makes sense for Linux as well. Applied, except for PTHREAD_BSD_SET_NAME, doesn't look like it should be necessary there. Can you please check if it builds now?

And yeah that's one of the two documents I used, the other being 2131024 "CDMA EVDO CnS Reference". Beware the docs are device-specific to some degree, 2130602 for instance is for MC8xxx and how much of it applies to other devices is not clear. Although for MC7710 it may happen to be quite accurate.

**Comment by BjWe** [comment]
Perfect! Thanks.

I've noticed that my card gives another rssi values back. 
1001 return the signal strength instead of dbm.

In my case I have to change 

> OiD(1001, GN, 4, umts)
> printf("RSSI -%idBm  BER ~ %.1f\n", 110 + S(0), 0.1 + 0.2*S(2));

to 

> printf("RSSI %idBm  BER ~ %.1f\n", -110 + S(0), 0.1 + 0.2*S(2));

**Comment by arsv** [comment]
Fixed, thanks.
